export const layout = {
  screenPadding: 16,
  cardPadding: 12,
  cardBorderRadius: 12,
  buttonBorderRadius: 10,
  inputBorderRadius: 10,
  avatarBorderRadius: 24,
  iconSize: 24,
  iconSizeSmall: 18,
  iconSizeLarge: 32,
  bottomTabHeight: 60,
  headerHeight: 56,
  cartBarHeight: 64,
  maxContentWidth: 480,
} as const;
