export const ACCESS_TOKEN_EXPIRY = "15m" as const;
export const ACCESS_TOKEN_EXPIRY_SECONDS = 900;
export const REFRESH_TOKEN_EXPIRY = "30d" as const;
export const REFRESH_TOKEN_EXPIRY_SECONDS = 2592000;
export const RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;
export const RATE_LIMIT_MAX_REQUESTS = 100;

export const CACHE_TTL_RESTAURANT_LIST_SECONDS = 300;
export const CACHE_TTL_RESTAURANT_DETAIL_SECONDS = 600;
export const CACHE_TTL_FOOD_MENU_SECONDS = 600;
export const CACHE_TTL_RECOMMENDATIONS_SECONDS = 300;
export const CACHE_TTL_ANALYTICS_SECONDS = 60;
